### ISSUE TITLE
`sign_items` convenience method

### ISSUE THREAD

**Issue by gjoseph92** [microsoft/planetary-computer-sdk-for-python#11]
It's a one-liner, but I find myself rewriting
```python
items = search.items_as_collection()
items = pystac_client.ItemCollection([pc.sign_assets(item) for item in items.features])
```
a lot. Might be nice to have built-in.

Could be even nicer to be able to pass in a Search and have it load and sign the items without making an intermediate ItemCollection?

**Comment by TomAugspurger** [comment]
Agreed! @kshepard or @lossyrob do you have thoughts on a preferred API? The two methods that stick out to me are `pc.sign_items` and `pc.sign_item_collection`. I prefer `sign_item_collection` since `sign_items` might be confused with `sign_assets`.

I hadn't considered passing in a search object, but that seems reasonable as well, unless I'm missing something.

**Comment by gjoseph92** [comment]
Frankly as a user, I'd most prefer if `pc.sign` just worked on whatever I passed into it and dispatched to the right function, and I didn't have to think about which name to use.

**Comment by lossyrob** [comment]
I was just about to comment the same; since we are trying for type safety there's a bit of type hoops to jump through with TypeVar for this, but we could do something like:

```python
from typing import TypeVar
from pystac import Asset, Item
from pystac_client import ItemCollection, Search  # not sure those are the exact types

T = TypeVar('T', str, Asset, Item, ItemCollection, Search)

def sign(obj: T) -> T:
  ...
```

and handle different types, while having the type checkers know which types would fit.
